version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres_db_payment
    env_file: ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT-3306}:${POSTGRES_DOCKER_PORT-3306}"
    volumes:
      - progresDB:/data/postgres
      
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  progresDB:
  redisDB: